stages:
  - build
  - release

# build versioned image and push to registry
build-plugin-job:
  stage: build
  image: golang:1.22-alpine
  script:
    - go mod download
    - go build -buildmode=plugin -o log.so log.go
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/
  artifacts:
    paths:
      - log.so

# if the commit is tagged with a version number and the branch is main, then release the version
release-version-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Releasing version $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
    name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_REF_NAME
